### PR TITLE
Set default option for working directory

### PR DESCRIPTION
**Pull request by karstens**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This isn't actually changing anything. The default working directory is already set.

**Comment by karstens** [comment]
Thats true. But it helps, if the {{options.cwd}} is needed somewhere else in the statements.

**Comment by sindresorhus** [comment]
But it's _not_ needed somewhere else, and your change is actually introducing a pretty hard to debug bug. You're overriding a property on the user supplied object. So if the user call this function twice with the same object, it will produce different result.

**Comment by karstens** [comment]
Should be local var , like 

```
var fromPath = opts.cwd || '.';
...
var resolved = resolveFrom(fromPath, pkg);
```

**Pull request closed without merging**
